### ISSUE TITLE
Rewrite to a path outside of rootDir

### ISSUE THREAD

**Issue by vprothais** [lwsjs/rewrite#12]
Hello,
I'm trying to use `local-web-server` for serving a documentation for a CSS framework.
My directory tree looks like that :
```
/
  dist/
    style.css
  public/
    index.html
```

The `public` folder contains the HTML documentation. In order to work well it needs files that are built in the `dist` folder. Those are the built files of the CSS framework.

I've tried to declare a rewrite like that : 
```
ws -d public  --rewrite '/dist/(.*) -> ../dist/$1'
```
But I get 403 in the browser and a Middleware error in the shell :
```
13:51:19: Middleware error
ForbiddenError: Forbidden
    at resolvePath (/home/vprothais/dev/oneI/node_modules/resolve-path/index.js:83:11)
    at send (/home/vprothais/dev/oneI/node_modules/koa-send/index.js:81:10)
    at serve (/home/vprothais/dev/oneI/node_modules/koa-static/index.js:44:24)
    at dispatch (/home/vprothais/dev/oneI/node_modules/koa-compose/index.js:42:32)
    at module.exports (/home/vprothais/dev/oneI/node_modules/koa-range/index.js:11:12)
    at dispatch (/home/vprothais/dev/oneI/node_modules/koa-compose/index.js:42:32)
    at etag (/home/vprothais/dev/oneI/node_modules/koa-etag/index.js:26:12)
    at dispatch (/home/vprothais/dev/oneI/node_modules/koa-compose/index.js:42:32)
    at conditional (/home/vprothais/dev/oneI/node_modules/koa-conditional-get/index.js:19:12)
    at dispatch (/home/vprothais/dev/oneI/node_modules/koa-compose/index.js:42:32)

```

It's probably for security reason.
I frequently use Apache aliases for folder outside of the root directory. I assumed it would work here.
Do I missed something with the configuration ?

Thank you for your help !

**Comment by 75lb** [comment]
Hi, only files within the specified root directory (`public` in your case) can be served - yes, this is for security reasons. 

Which OS are you using? If mac or linux, have you tried creating a symlink within `public` which points to `dist`? 

Another option is set the root to a directory higher up the file system, then use [`--blacklist`](https://github.com/lwsjs/local-web-server/wiki/How-to-blacklist-certain-routes) to block sensitive or private directories. 

The most efficient solution is to ensure your `public` directory contains all the files you wish to expose, that is the general convention..

**Comment by vprothais** [comment]
Ok thank you.

That's right, a rewrite and an alias are different things.

I didn't want to use symlink because we can have contributors using different OS and symlink in windows needs admin rights. But  I found the package `symlink-dir` that seems to work on every OS. I've tried with it and it works well.

Thank you for you time.

Have a nice day ;)

**Comment by 75lb** [comment]
have a good day too 👍
