### ISSUE TITLE
Error: Cannot find module 'req-then'

### ISSUE THREAD

**Issue by 5im-0n** [lwsjs/rewrite#5]
11:45:29 AM: Middleware error
Error: Cannot find module 'req-then'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Promise (node_modules\local-web-server\node_modules\lws-rewrite\index.js:113:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by 5im-0n** [comment]
Removed in 1475987d7319fd05aa3294561b7177a891614d5d but unfortunately still used in https://github.com/lwsjs/rewrite/blob/master/index.js#L115

**Comment by 75lb** [comment]
I'll fix that - apologies, i started this WIP late last night and should have pushed it to a branch while incomplete..

**Comment by 5im-0n** [comment]
No problem. I was just testing some things and tought you may have missed that.
